sudo: false

branches:
    only:
        - master

addons:
    apt:
        package:
            - doxygen

script:
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GH_REPO_TOKEN
    on:
        branch: master
